# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Balance.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BalanceForm(object):
    def setupUi(self, BalanceForm):
        BalanceForm.setObjectName("BalanceForm")
        BalanceForm.resize(686, 524)
        self.verticalLayout = QtWidgets.QVBoxLayout(BalanceForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(BalanceForm)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.CMBoxClockwise = QtWidgets.QComboBox(self.tab)
        self.CMBoxClockwise.setObjectName("CMBoxClockwise")
        self.CMBoxClockwise.addItem("")
        self.CMBoxClockwise.addItem("")
        self.horizontalLayout_2.addWidget(self.CMBoxClockwise)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.DSBoxKeyPos = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxKeyPos.setMinimum(-360.0)
        self.DSBoxKeyPos.setMaximum(360.0)
        self.DSBoxKeyPos.setObjectName("DSBoxKeyPos")
        self.horizontalLayout_15.addWidget(self.DSBoxKeyPos)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.DSBoxXPos = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxXPos.setMinimum(-360.0)
        self.DSBoxXPos.setMaximum(360.0)
        self.DSBoxXPos.setObjectName("DSBoxXPos")
        self.horizontalLayout_14.addWidget(self.DSBoxXPos)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.DSBoxYPos = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxYPos.setMinimum(-360.0)
        self.DSBoxYPos.setMaximum(360.0)
        self.DSBoxYPos.setObjectName("DSBoxYPos")
        self.horizontalLayout_13.addWidget(self.DSBoxYPos)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.DSBoxXamp = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxXamp.setMaximum(1000.0)
        self.DSBoxXamp.setObjectName("DSBoxXamp")
        self.horizontalLayout_12.addWidget(self.DSBoxXamp)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.DSBoxXpha = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxXpha.setMinimum(-360.0)
        self.DSBoxXpha.setMaximum(360.0)
        self.DSBoxXpha.setObjectName("DSBoxXpha")
        self.horizontalLayout_11.addWidget(self.DSBoxXpha)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.DSBoxXlag = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxXlag.setMinimum(-360.0)
        self.DSBoxXlag.setMaximum(360.0)
        self.DSBoxXlag.setObjectName("DSBoxXlag")
        self.horizontalLayout_10.addWidget(self.DSBoxXlag)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.DSBoxYamp = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxYamp.setMaximum(1000.0)
        self.DSBoxYamp.setObjectName("DSBoxYamp")
        self.horizontalLayout_9.addWidget(self.DSBoxYamp)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.DSBoxYpha = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxYpha.setMinimum(-360.0)
        self.DSBoxYpha.setMaximum(360.0)
        self.DSBoxYpha.setObjectName("DSBoxYpha")
        self.horizontalLayout_8.addWidget(self.DSBoxYpha)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.DSBoxYlag = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxYlag.setMinimum(-360.0)
        self.DSBoxYlag.setMaximum(360.0)
        self.DSBoxYlag.setObjectName("DSBoxYlag")
        self.horizontalLayout_7.addWidget(self.DSBoxYlag)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.TextXweightpos = QtWidgets.QLineEdit(self.tab)
        self.TextXweightpos.setEnabled(True)
        self.TextXweightpos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TextXweightpos.setDragEnabled(True)
        self.TextXweightpos.setReadOnly(True)
        self.TextXweightpos.setObjectName("TextXweightpos")
        self.horizontalLayout_6.addWidget(self.TextXweightpos)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.TextYweightpos = QtWidgets.QLineEdit(self.tab)
        self.TextYweightpos.setEnabled(True)
        self.TextYweightpos.setDragEnabled(True)
        self.TextYweightpos.setReadOnly(True)
        self.TextYweightpos.setObjectName("TextYweightpos")
        self.horizontalLayout_5.addWidget(self.TextYweightpos)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.DSBoxMass = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxMass.setMaximum(100000.0)
        self.DSBoxMass.setObjectName("DSBoxMass")
        self.horizontalLayout_17.addWidget(self.DSBoxMass)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_21.addWidget(self.label_17)
        self.DSBoxRPM = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxRPM.setMaximum(100000.0)
        self.DSBoxRPM.setObjectName("DSBoxRPM")
        self.horizontalLayout_21.addWidget(self.DSBoxRPM)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.DSBoxRadius = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxRadius.setMaximum(15000.0)
        self.DSBoxRadius.setObjectName("DSBoxRadius")
        self.horizontalLayout_20.addWidget(self.DSBoxRadius)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.DSBoxWeight = QtWidgets.QDoubleSpinBox(self.tab)
        self.DSBoxWeight.setMaximum(100000.0)
        self.DSBoxWeight.setObjectName("DSBoxWeight")
        self.horizontalLayout_19.addWidget(self.DSBoxWeight)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.TextUnitKgf = QtWidgets.QLineEdit(self.tab)
        self.TextUnitKgf.setEnabled(True)
        self.TextUnitKgf.setDragEnabled(True)
        self.TextUnitKgf.setReadOnly(True)
        self.TextUnitKgf.setObjectName("TextUnitKgf")
        self.horizontalLayout_18.addWidget(self.TextUnitKgf)
        self.horizontalLayout_18.setStretch(0, 9)
        self.horizontalLayout_18.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.TextAllKgf = QtWidgets.QLineEdit(self.tab)
        self.TextAllKgf.setEnabled(True)
        self.TextAllKgf.setDragEnabled(True)
        self.TextAllKgf.setReadOnly(True)
        self.TextAllKgf.setObjectName("TextAllKgf")
        self.horizontalLayout_16.addWidget(self.TextAllKgf)
        self.horizontalLayout_16.setStretch(0, 9)
        self.horizontalLayout_16.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.TextPercent = QtWidgets.QLineEdit(self.tab)
        self.TextPercent.setEnabled(True)
        self.TextPercent.setDragEnabled(True)
        self.TextPercent.setReadOnly(True)
        self.TextPercent.setObjectName("TextPercent")
        self.horizontalLayout_4.addWidget(self.TextPercent)
        self.horizontalLayout_4.setStretch(0, 9)
        self.horizontalLayout_4.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LayoutTab1Plot = QtWidgets.QVBoxLayout()
        self.LayoutTab1Plot.setObjectName("LayoutTab1Plot")
        self.verticalLayout_4.addLayout(self.LayoutTab1Plot)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.CheckDispAy = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAy.setChecked(True)
        self.CheckDispAy.setObjectName("CheckDispAy")
        self.gridLayout.addWidget(self.CheckDispAy, 0, 4, 1, 1)
        self.CheckDispPyLabel = QtWidgets.QCheckBox(self.tab)
        self.CheckDispPyLabel.setChecked(True)
        self.CheckDispPyLabel.setObjectName("CheckDispPyLabel")
        self.gridLayout.addWidget(self.CheckDispPyLabel, 0, 8, 1, 1)
        self.CheckDispPy = QtWidgets.QCheckBox(self.tab)
        self.CheckDispPy.setChecked(True)
        self.CheckDispPy.setObjectName("CheckDispPy")
        self.gridLayout.addWidget(self.CheckDispPy, 0, 7, 1, 1)
        self.CheckDispAyLabel = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAyLabel.setChecked(True)
        self.CheckDispAyLabel.setObjectName("CheckDispAyLabel")
        self.gridLayout.addWidget(self.CheckDispAyLabel, 0, 5, 1, 1)
        self.CheckDispAx = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAx.setChecked(True)
        self.CheckDispAx.setObjectName("CheckDispAx")
        self.gridLayout.addWidget(self.CheckDispAx, 0, 0, 1, 1)
        self.CheckDispPx = QtWidgets.QCheckBox(self.tab)
        self.CheckDispPx.setChecked(True)
        self.CheckDispPx.setObjectName("CheckDispPx")
        self.gridLayout.addWidget(self.CheckDispPx, 0, 2, 1, 1)
        self.CheckDispPxLabel = QtWidgets.QCheckBox(self.tab)
        self.CheckDispPxLabel.setChecked(True)
        self.CheckDispPxLabel.setObjectName("CheckDispPxLabel")
        self.gridLayout.addWidget(self.CheckDispPxLabel, 0, 3, 1, 1)
        self.CheckDispAxLabel = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAxLabel.setChecked(True)
        self.CheckDispAxLabel.setObjectName("CheckDispAxLabel")
        self.gridLayout.addWidget(self.CheckDispAxLabel, 0, 1, 1, 1)
        self.BTNHelp = QtWidgets.QPushButton(self.tab)
        self.BTNHelp.setObjectName("BTNHelp")
        self.gridLayout.addWidget(self.BTNHelp, 1, 8, 1, 1)
        self.CheckDispAll = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAll.setChecked(True)
        self.CheckDispAll.setObjectName("CheckDispAll")
        self.gridLayout.addWidget(self.CheckDispAll, 1, 7, 1, 1)
        self.CheckDispQx = QtWidgets.QCheckBox(self.tab)
        self.CheckDispQx.setChecked(True)
        self.CheckDispQx.setObjectName("CheckDispQx")
        self.gridLayout.addWidget(self.CheckDispQx, 1, 4, 1, 1)
        self.CheckDispQy = QtWidgets.QCheckBox(self.tab)
        self.CheckDispQy.setChecked(True)
        self.CheckDispQy.setObjectName("CheckDispQy")
        self.gridLayout.addWidget(self.CheckDispQy, 1, 5, 1, 1)
        self.CheckDispAxAngle = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAxAngle.setEnabled(False)
        self.CheckDispAxAngle.setObjectName("CheckDispAxAngle")
        self.gridLayout.addWidget(self.CheckDispAxAngle, 1, 0, 1, 1)
        self.CheckDispPxAngle = QtWidgets.QCheckBox(self.tab)
        self.CheckDispPxAngle.setEnabled(False)
        self.CheckDispPxAngle.setObjectName("CheckDispPxAngle")
        self.gridLayout.addWidget(self.CheckDispPxAngle, 1, 1, 1, 1)
        self.CheckDispAyAngle = QtWidgets.QCheckBox(self.tab)
        self.CheckDispAyAngle.setEnabled(False)
        self.CheckDispAyAngle.setObjectName("CheckDispAyAngle")
        self.gridLayout.addWidget(self.CheckDispAyAngle, 1, 2, 1, 1)
        self.CheckDispPyAngle = QtWidgets.QCheckBox(self.tab)
        self.CheckDispPyAngle.setEnabled(False)
        self.CheckDispPyAngle.setObjectName("CheckDispPyAngle")
        self.gridLayout.addWidget(self.CheckDispPyAngle, 1, 3, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.setStretch(0, 15)
        self.verticalLayout_4.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(BalanceForm)
        QtCore.QMetaObject.connectSlotsByName(BalanceForm)

    def retranslateUi(self, BalanceForm):
        _translate = QtCore.QCoreApplication.translate
        BalanceForm.setWindowTitle(_translate("BalanceForm", "Form"))
        self.label.setText(_translate("BalanceForm", "转向"))
        self.CMBoxClockwise.setItemText(0, _translate("BalanceForm", "顺时针"))
        self.CMBoxClockwise.setItemText(1, _translate("BalanceForm", "逆时针"))
        self.label_2.setText(_translate("BalanceForm", "键相位置°"))
        self.label_3.setText(_translate("BalanceForm", "X向位置°"))
        self.label_4.setText(_translate("BalanceForm", "Y向位置°"))
        self.label_5.setText(_translate("BalanceForm", "X向幅值μm (Ax)"))
        self.label_6.setText(_translate("BalanceForm", "X向相位°  (Ax)"))
        self.label_7.setText(_translate("BalanceForm", "X向滞后角  (Ax)"))
        self.label_8.setText(_translate("BalanceForm", "Y向幅值μm (Ay)"))
        self.label_9.setText(_translate("BalanceForm", "Y向相位°  (Ay)"))
        self.label_10.setText(_translate("BalanceForm", "Y向滞后角  (Ay)"))
        self.label_11.setText(_translate("BalanceForm", "按X向加重位置\n"
"(键相逆转向)°(Qx)"))
        self.TextXweightpos.setText(_translate("BalanceForm", "0"))
        self.label_12.setText(_translate("BalanceForm", "按Y向加重位置\n"
"(键相逆转向)°(Qy)"))
        self.TextYweightpos.setText(_translate("BalanceForm", "0"))
        self.label_18.setText(_translate("BalanceForm", "转子质量kg"))
        self.label_17.setText(_translate("BalanceForm", "转速rpm"))
        self.label_20.setText(_translate("BalanceForm", "加重半径mm"))
        self.label_19.setText(_translate("BalanceForm", "试加重质量g"))
        self.label_16.setText(_translate("BalanceForm", "加重1g产生激振力kgf    "))
        self.TextUnitKgf.setText(_translate("BalanceForm", "0"))
        self.label_15.setText(_translate("BalanceForm", "试加重产生总的激振力kgf"))
        self.TextAllKgf.setText(_translate("BalanceForm", "0"))
        self.label_13.setText(_translate("BalanceForm", "试加重激振力与转子重力比%"))
        self.TextPercent.setText(_translate("BalanceForm", "0"))
        self.CheckDispAy.setText(_translate("BalanceForm", "显示Ay"))
        self.CheckDispPyLabel.setText(_translate("BalanceForm", "显示Py标签"))
        self.CheckDispPy.setText(_translate("BalanceForm", "显示Py"))
        self.CheckDispAyLabel.setText(_translate("BalanceForm", "显示Ay标签"))
        self.CheckDispAx.setText(_translate("BalanceForm", "显示Ax"))
        self.CheckDispPx.setText(_translate("BalanceForm", "显示Px"))
        self.CheckDispPxLabel.setText(_translate("BalanceForm", "显示Px标签"))
        self.CheckDispAxLabel.setText(_translate("BalanceForm", "显示Ax标签"))
        self.BTNHelp.setText(_translate("BalanceForm", "帮助"))
        self.CheckDispAll.setText(_translate("BalanceForm", "显示所有"))
        self.CheckDispQx.setText(_translate("BalanceForm", "显示Qx"))
        self.CheckDispQy.setText(_translate("BalanceForm", "显示Qy"))
        self.CheckDispAxAngle.setText(_translate("BalanceForm", "Ax角注"))
        self.CheckDispPxAngle.setText(_translate("BalanceForm", "Px角注"))
        self.CheckDispAyAngle.setText(_translate("BalanceForm", "Ay角注"))
        self.CheckDispPyAngle.setText(_translate("BalanceForm", "Py角注"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BalanceForm", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("BalanceForm", "Tab 2"))

